# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbaedadbbcacf6223ebe722c3feae3aa2883fa44e8ab4d4996cee74a9764ee34691712757e3ede40ab9647c9bcbff13b662dbce3f94d89e183ceadfa322474ef

test:
  secret_key_base: fa35177c679dd85340a3ac3cf43413cb451d74e65eb289288c10e2d2ec07800c4b0f0a6616b7d2e3b5206e4f3b52b60daac431b60a7f50a7017641d509e14289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
